version: '3.7'

services:

  app:
    image: node:8.11.3-slim
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    ports:
      - 3000:3000
    command: npm start

  cmd:
    image: node:8.11.3-slim
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: /bin/bash